#!/usr/bin/env node
/**
 * Token build step — Figma → CSS custom properties.
 *
 * Reads design/figma-tokens.json (the values exported from the Figma design
 * system) and regenerates src/styles/tokens/_generated.css.
 *
 * This is the deterministic half of the design↔code sync: token VALUES live in
 * Figma, this script writes them into code 1:1. Do NOT hand-edit the generated
 * file — change the value in Figma, re-export the JSON, then run `npm run tokens`.
 *
 * What it emits:
 *   - Color  : primitives as hex (or rgba when alpha < 1); semantic tokens as
 *              `var(--alias)` references so the alias chain is preserved.
 *   - Spacing/Radius/Grid : px (except a small unitless denylist).
 *   - Typography : font SIZES only (--size-*). Font FAMILIES stay hand-authored
 *                  in typography.css so the fallback stacks are preserved.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const SRC = resolve(root, "design/figma-tokens.json");
const OUT = resolve(root, "src/styles/tokens/_generated.css");

// FLOAT tokens that must stay unitless (no px suffix).
const UNITLESS = new Set(["grid-columns"]);
// Typography STRING tokens we deliberately do NOT generate (kept hand-authored
// in typography.css to preserve font fallback stacks).
const SKIP = new Set(["font-serif", "font-sans"]);

function hexToRgba(hex, alpha) {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function renderValue(v) {
  if (v.value.alias) return `var(--${v.value.alias})`;
  if (v.type === "COLOR") {
    const { color, alpha } = v.value;
    return alpha != null && alpha < 1 ? hexToRgba(color, alpha) : color;
  }
  if (v.type === "FLOAT") {
    return UNITLESS.has(v.css) ? String(v.value.literal) : `${v.value.literal}px`;
  }
  return String(v.value.literal); // STRING
}

function main() {
  const { collections } = JSON.parse(readFileSync(SRC, "utf8"));
  const lines = [
    "/* ============================================================",
    "   AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT.",
    "   Source of truth: Figma design system (design/figma-tokens.json).",
    "   Regenerate with:  npm run tokens",
    "   ============================================================ */",
    ":root {",
  ];

  let count = 0;
  for (const [group, vars] of Object.entries(collections)) {
    lines.push(`\n  /* — ${group} — */`);
    for (const v of vars) {
      if (SKIP.has(v.css)) continue;
      lines.push(`  --${v.css}: ${renderValue(v)};`);
      count++;
    }
  }
  lines.push("}", "");

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n"), "utf8");
  console.log(`✓ Wrote ${count} tokens → ${OUT.replace(root + "/", "")}`);
}

main();
